### ISSUE TITLE
[Bug] Synthetic Recorder not working in MacOS 15.0 Sequoia

### ISSUE THREAD

**Issue by mnizamk** [elastic/synthetics-recorder#533]
### Bug summary

Hi,

The Elastic Synthetic recorder is not working on **MacOS Sequoia v15.0** , when we hit the Start recording getting below error.

`Unhandled Promise Rejection Error: Page closed at CRSession.<anonymous> (/private/var/folders/_4/pmb9slfs3lxdrs8q6wf1670w0000gr/T/AppTranslocation/A352FFA7-37A7-4D41-A63F-93C95EE1C5A4/d/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crPage.js:377:54) at Object.onceWrapper (node:events:641:28) at CRSession.emit (node:events:539:35) at /private/var/folders/_4/pmb9slfs3lxdrs8q6wf1670w0000gr/T/AppTranslocation/A352FFA7-37A7-4D41-A63F-93C95EE1C5A4/d/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crConnection.js:211:39`

Thanks,

### Recorder Version

1.3.0

### Steps to reproduce

Issue:

1. Start the recorder
2. Key in URL "https://google.com/"
3. Click Start

### Expected behavior

Chromium browser should open, instead error thrown

**Comment by jvelloen** [comment]
Identical behaviour on **MacOS Sequoia 15.1** and Recorder **Version 1.3.0 (1.3.0.2)**:

`Unhandled Promise Rejection
Error: Page closed
    at CRSession.<anonymous> (/Applications/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crPage.js:377:54)
    at Object.onceWrapper (node:events:641:28)
    at CRSession.emit (node:events:539:35)
    at /Applications/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crConnection.js:211:39`

**Comment by natashascribes** [comment]
I am facing the same issue after Mac upgraded to 15.1.1

**Comment by venkatjj86** [comment]
Hi Team,

I'm getting same issue post upgraded my Mac device to 15.1.1. 

It will be really help helpful, if we get any solution/advise. 

Thank you.

**Comment by jrentsch** [comment]
Anyone have any updates on this?

I am seeing the same error.

**Comment by justinkambic** [comment]
Hi, thank you for your patience.

We're working on getting a new version of the recorder built and released as soon as possible. Sorry for the delay here, there's been a bit of internal churn on this product but we have been and are hard at work on the issue (and a few other bug fixes). Most of the issues we were facing debugging and resolving the core problem are done, and we hope to be able to release the next version soon.

**Comment by limxf** [comment]
Same as me, hope to get the fix soon. 

MacOS: 15.4 (24E248)
Recorder: synthetics-recorder-1.3.0-mac-arm64.dmg

```
Error: Page closed
at CRSession.<anonymous> (/Applications/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crPage.js:377:54)
at Object.onceWrapper (node:events:641:28)
at CRSession.emit (node:events:539:35)
at /Applications/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crConnection.js:211:39
```

**Comment by justinkambic** [comment]
Update here - we have resolved most of the issues with our new release pipeline/code signing. There are some small issues that remain, but we are actively working on fixing those and are hopeful they will not block us much longer. I apologize for the long delay here.

**Comment by bernarmn-mnb** [comment]
customer needs to use this recorder, is there a workaround, it appears to fail no matter what we try

**Comment by nekirc** [comment]
MacOS: 15.4.1 (24E263)
Macbook Air Apple M1

Try to record url: https://google.com

Got error:

Unhandled Promise Rejection

`Error: Page closed
at CRSession.<anonymous> (/Applications/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crPage.js:377:54)
at Object.onceWrapper (node:events:641:28)
at CRSession.emit (node:events:539:35)
at /Applications/Elastic Synthetics Recorder.app/Contents/Resources/app.asar/node_modules/playwright-core/lib/server/chromium/crConnection.js:211:39`

**Comment by ap-elmo** [comment]
Receiving the same issue! Would be good to get it resolved if possible.

**Comment by TomonoriSoejima** [comment]
The user I am dealing with says they tested [v1.4.14](https://github.com/elastic/synthetics-recorder/releases/tag/v1.4.14) and it works!
